services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: ${API_URL}
        DATABASE_URL: ${DATABASE_URL}
        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        ALLOWED_EMAIL_DOMAIN: ${ALLOWED_EMAIL_DOMAIN}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - dokploy-network
    expose:
      - "8000"
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      - "traefik.http.routers.itdbctf.rule=Host(`itdbctf.duckdns.org`)"
      - traefik.http.routers.itdbctf.entrypoints=websecure
      - traefik.http.routers.itdbctf.tls.certResolver=letsencrypt
      - traefik.http.routers.itdbctf.priority=1
      - traefik.http.routers.itdbctf.service=itdbctf
      - traefik.http.services.itdbctf.loadbalancer.server.port=8000
    volumes:
      - archivos_retos:/app/FILES_ITDB_CTF/retos

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - dokploy-network

volumes:
  archivos_retos:

networks:
  dokploy-network:
    external: true